#4 feat: add labels for rubik's cube sides
vlrsmlkv/rubiks-cube pull request #5
Opened 2022-08-15 16:13 UTC by vlrsmlkv

Added labels for rubik's cube sides and label switcher.

2022-08-18 20:09 UTC, OUghTMS requested changes

2022-08-18 20:09 UTC, OUghTMS commented on src/components/App.jsx
> +  const [isLabelSwitchChecked, setIsLabelSwitchChecked] = useState(false);
Move all states together

2022-08-18 20:09 UTC, OUghTMS commented on src/components/App.jsx
> +  const [isLabelSwitchChecked, setIsLabelSwitchChecked] = useState(false);
line to line

2022-08-22 10:20 UTC, vlrsmlkv commented on src/components/App.jsx
> +  const [isLabelSwitchChecked, setIsLabelSwitchChecked] = useState(false);
done ✅

2022-08-22 17:58 UTC, OUghTMS approved these changes

2022-08-22 17:58 UTC, merged