#3 feat: add scramble button
vlrsmlkv/rubiks-cube pull request #6
Opened 2022-08-16 20:34 UTC by vlrsmlkv

Added scramble button.

2022-08-18 20:12 UTC, OUghTMS requested changes

2022-08-18 20:12 UTC, OUghTMS commented on src/components/App.jsx
> +  const [scrambleRotationCounter, setScrambleRotationCounter] = useState(0);
same

2022-08-18 20:12 UTC, OUghTMS commented on src/components/App.jsx
> +  const getScrambleRandomParams = () => {
move into utils

2022-08-22 10:45 UTC, vlrsmlkv commented on src/components/App.jsx
> +  const [scrambleRotationCounter, setScrambleRotationCounter] = useState(0);
done ✅

2022-08-22 10:45 UTC, vlrsmlkv commented on src/components/App.jsx
> +  const getScrambleRandomParams = () => {
done ✅

2022-08-22 18:01 UTC, OUghTMS approved these changes

2022-08-22 18:32 UTC, merged